## Numpy Array And Basics

Learn About Numpy With Chai Aur Code

In [1]:
import numpy as np

### Creating Array From List

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1-D Array:",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2-D Array:", arr_2d)



1-D Array: [1 2 3 4 5]
2-D Array: [[1 2 3]
 [4 5 6]]


### List VS Numpy Array

In [3]:
py_list = [1,2,3]
print("Python List Multiplication:", py_list * 2)

np_array = np.array([1,2,3]) # Eelement Wise Multiplication
print("Python Array Multiplication:", np_array * 2)

import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation Time:",time.time()- start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Operation Time:",time.time()- start)


Python List Multiplication: [1, 2, 3, 1, 2, 3]
Python Array Multiplication: [2 4 6]

 List Operation Time: 0.1619560718536377

 Numpy Operation Time: 0.010230541229248047


### Creating Array From Scratch

In [ ]:
zeros = np.zeros((3, 4))
print("Zeros array: \n",zeros)

ones = np.ones((2,3))
print("Ones Array:\n",ones)

full = np.full((2,2),7)
print("Full Array:\n",full)

random = np.random.random((2,3))
print("Random Array:\n", random)

sequence = np.arange(0, 10, 2)
print("Sequence Array:\n", sequence)

Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full Array:
 [[7 7]
 [7 7]]
Random Array:
 [[0.87439758 0.50895681 0.69075713]
 [0.44690008 0.41295443 0.95026393]]
Sequence Array: [0 2 4 6 8]


### Vector,Matrix And Tensor

In [9]:
vector = np.array((1, 2, 3))
print("Vector: ",vector)

matrix = np.array([[1, 2, 3],[4, 5, 6]])
print("Matrix:",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tesor: ",tensor)

Vector:  [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tesor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [14]:
arr = np.array([[1,2,3],[4,5,6]])

print("Shape of Array:",arr.shape)
print("Dimension of Array:",arr.ndim)
print("Size of Array:",arr.size)
print("Data Type of array:",arr.dtype)


Shape of Array: (2, 3)
Dimension of Array: 2
Size of Array: 6
Data Type of array: int64


### Array Reshaping

In [18]:
arr = np.arange(12)
print("Original Array:",arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped Array:",reshaped)

flattened = reshaped.flatten()
print("\n Flattened Array:",flattened)

# Revel(Returns  View, Instead of Copy)
raveled = reshaped.ravel()
print("\n raveled Array:",raveled)

# Transpose
transpose = reshaped.T
print("\n Transpose Array:",transpose)


Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled Array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose Array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
