## Numpy Array Operations

In [2]:
import numpy as np

## Slicing And Indexing

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing:",arr[2:7])
print("With Step:",arr[1:8:2])
print("Negative indexing:",arr[-3])

Basic Slicing: [3 4 5 6 7]
With Step: [2 4 6 8]
Negative indexing: 8


In [11]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element:",arr_2d[1,2])
print("Entire Raw:",arr_2d[1])
print("Entire Column:",arr_2d[:,1])

Specific Element: 6
Entire Raw: [4 5 6]
Entire Column: [2 5 8]


## Sorting

In [18]:
unsorted = np.array([3,4,1,2,9,8,6,7,5])
print("sorted Array:",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("sorted 2D Array By Column:",np.sort(arr_2d_unsorted, axis=0))
print("sorted 2D Array By Raw:",np.sort(arr_2d_unsorted, axis=1))

sorted Array: [1 2 3 4 5 6 7 8 9]
sorted 2D Array By Column: [[1 1]
 [2 2]
 [3 3]]
sorted 2D Array By Raw: [[1 3]
 [1 2]
 [2 3]]


## Filter

In [19]:
numbers = np.array([1,2,3,4,5,6,7,8,9])
even_number = numbers[numbers%2 == 0]
print("Even Numbers:",even_number)

Even Numbers: [2 4 6 8]


## Filter With Mask

In [ ]:
mask = numbers > 5
print("Numbers Greater Than 5:",numbers[mask])
print("Numbers Greater Than 5:",numbers[numbers>5])

Numbers Greater Than 5: [6 7 8 9]
Numbers Greater Than 5: [6 7 8 9]


## Fancy Indexing VS np.where()

In [24]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("Numpy Where:",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8]),)
Numpy Where: [6 7 8 9]


In [ ]:
condition_array = np.where(numbers > 5)
print(condition_array)

condition_array = np.where(numbers > 5, numbers*2, numbers) #When Greter Than 5 is Numbers Multiply by 2
print(condition_array)

# if numbers>5:
#     numbers*4
# else:
#     numbers

(array([5, 6, 7, 8]),)
[ 1  2  3  4  5 12 14 16 18]


### Adding And Removing Data

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1+arr2
combined = np.concatenate((arr1,arr2))
print("Combine Array:",combined)



Combine Array: [1 2 3 4 5 6]


### Array Compatibility

In [36]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatability Shapes:",a.shape == b.shape)

Compatability Shapes: True


In [38]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("With The Column:",with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With The Column: [[1 2 7]
 [3 4 8]]


In [40]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("Array After Deletion",deleted)

Array After Deletion [1 2 4 5]
