In [1]:
import numpy as np

Basic Array Creation

In [ ]:
arr = np.array([1,2,3,4,5]) # Single Array Called Vecotor And Two array in One List is Called Multidimension Array like row and Column wise.
arr

array([1, 2, 3, 4, 5])

In [6]:
a = [1,2,3,4,5,"vaibhav"]
a

[1, 2, 3, 4, 5, 'vaibhav']

In [ ]:
np.array(a) # All Array in One Type String And You Give One Float Then Store in Float

array(['1', '2', '3', '4', '5', 'vaibhav'], dtype='<U21')

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [13]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [16]:
arr = np.zeros((2,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
arr = np.ones((3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

Random Generation Function

In [21]:
np.random.rand(10)

array([0.99815906, 0.87155689, 0.51996302, 0.83639472, 0.44555534,
       0.88259438, 0.71979548, 0.1916864 , 0.28126136, 0.69232198])

In [26]:
np.random.randn(10)

array([ 0.04590309, -1.67642428,  2.02485043,  1.51863077,  0.0503355 ,
        0.24385196,  1.11064427, -0.40134246, -2.2337824 ,  0.54144922])

In [31]:
np.random.randint(10,20,5)

array([11, 13, 14, 17, 17], dtype=int32)

Array Attributes

In [32]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape # how Many Column and Rows

(3, 3)

In [34]:
arr.size

9

In [35]:
arr.dtype

dtype('int64')

Array Methods

In [37]:
arr.min()

np.int64(1)

In [38]:
arr.max()

np.int64(9)

In [39]:
arr.sum()

np.int64(45)

In [41]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [ ]:
arr.mean()

np.float64(5.0)

In [43]:
arr.std()

np.float64(2.581988897471611)

In [44]:
arr.argmax()

np.int64(8)

In [46]:
arr.argmin()

np.int64(0)

Reshaping And Resizing

In [47]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5) # Reshape And Resize : Reshape Array And Store in Variable is Resize Array.

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])