In [1]:
import numpy as np

**ARRAY OPERATIONS**

Arithmetic Operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1-a2

array([-5, -5, -5, -5, -5])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1//a2

array([0, 0, 0, 0, 0])

In [8]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [14]:
arr1 = np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr1 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Broadcasting

In [9]:
l = [10,20,30,40]
arr = np.array(l)

In [10]:
arr + 10

array([20, 30, 40, 50])

In [16]:
arr *2

array([20, 40, 60, 80])

Deep And Shallow Copy

In [37]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [39]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
a[4:6] * 10

array([50, 60])

In [43]:
a
b=a.copy()

In [44]:
b[0] = 99

In [45]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [48]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [49]:
A

array([[1, 2],
       [3, 4]])

In [50]:
B

array([[5, 6],
       [7, 8]])

In [51]:
A * B

array([[ 5, 12],
       [21, 32]])

In [ ]:
A @ B  # Multiplication of Array.
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [54]:
A

array([[1, 2],
       [3, 4]])

In [55]:
A.T

array([[1, 3],
       [2, 4]])

**Advance Array Manipulation**

Staking Array

In [73]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [61]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [65]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [81]:
a = np.vsplit(c,4)
a

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [82]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
