In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr_slice = arr[2:5]
arr_slice

array([13, 14, 15])

NUMPY INDEXING AND SLICING OF MATRIX

In [16]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [23]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [25]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [26]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**BOOLEAN INDEXING**

In [28]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
bool_index = arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [30]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])